### ISSUE TITLE
Support for converting Bootstrap 4 to less

### ISSUE THREAD

**Issue by mediafreakch** [mediafreakch/less-plugin-sass2less#1]
Currently the plugin cannot convert all of Bootstrap 4 (`v4.0.0-alpha.6`). They are using some quite advanced SASS functions that the plugin doesn't convert yet. The LESS compiler will throw errors if you try to compile the converted files. 

Here's a list of what I found so far:

- [ ] `@each`
- [ ] `comparable()`
- [ ] `@warn` - afaik there's no equivalent in LESS, maybe just strip it?
- [ ] `@else if (not)` - this one might be tricky
- [ ] `map-values()` 
- [ ] `( 0: ( x: 0, y: 0))` (maps) - there is no map data-type in less. maybe this can help: https://github.com/seven-phases-max/less-plugin-lists

I'll start working from the top. Ideas about how to convert / support the `map` data-type in LESS would be appreciated.

**Comment by matthew-dean** [comment]
Would this help you as a starting point? https://github.com/Crunch/Granola/blob/master/lib/map.js

It's a work-in-progress, so there might be some edge cases where the value doesn't evaluate IIRC (haven't worked on it in a while). But I got it to a point where it was working pretty well for most uses.

I could probably release it as a separate Less.js plugin at some point.

It allows definitions like this:
```less
@set {
        options {
            ui: default;
            elements: default;
            theme: default;
        }
        colors {
        	dark {
        	    color: black;
        	}
        	light {
        	    color: white;
        	}
        }
    }
```
And then you can get a value with a get() function.
```less
.box {
  color: get('colors.dark.color');
}
```

**Comment by matthew-dean** [comment]
Btw, something like maps might come to native Less. See the discussion at: https://github.com/less/less-meta/issues/12

The thread is long, but the proposal is to allow accessing variables / properties of namespaces & mixins, with a syntax like:
```less
#namespace {
  prop1: value;
  @var1: value;
}
.box {
  value1: #namespace['prop1'];
  value2: #namespace['@var1'];
}
```
That would effectively turn ANY single-selector ruleset into a map, so there'd be no need for another "data type".

**Comment by matthew-dean** [comment]
And I wrote an "each" function here: https://github.com/less/less.js/pull/2786/commits/f52b0736015d69f01e9be3257b039f2f332a613f

Yes, `@warn` has no equivalent or current value in Less.

Elseif is a little trickier. There's an order of evaluation, but not an order of operations, since the languages are dissimilar in their approach. See: https://getcrunch.co/2015/10/08/less-the-worlds-most-misunderstood-css-pre-processor/ (Not trying to be showy, just hoping these links will help you, because I think this is a great project to have working.

Mixins match based on guards, but guards don't carry forward the result of the previous test.

So you can do:
```sass
@if($a = 1) { }
@if($a = 2) { }
```
But it's much trickier to do this:
```sass
@if($a = 1) { }
@elseif($a > 0) { }
```
...because Less is not a _program_ like Sass is. Each block is independently evaluated by evaluation rules. However... maybe you could do it like:
```less
.mixin() when (@a = 1) { }
.mixin() when (not (@a = 1)) and (@a > 0) { }
```
So, you have to exclusively negate the first condition if you want to only evaluate the second if the first doesn't match. And, of course, you'd have to negate _two_ conditions if there are multiple elseifs. (And then you immediately call the mixin.)

So, an if / elseif / else would be like:
```less
.mixin() when (@a = 1) { }
.mixin() when (not (@a = 1)) and (@a > 0) { }
.mixin() when (default()) { }
.mixin();
```
(Or you do these things in a plugin.)

**Comment by matthew-dean** [comment]
The one thing you're going to need to be careful about is variable scope and lazy-loading. Sass's variable scope is different, and in Sass, variables can't be referenced before they're defined (unlike Less).

So, in Sass, you get:
```sass
$var: 1;
.box {
  $var: 2;
  val: $var; // value is 2
  $var: 3;
}
$new_var: $var;  // value is 3
```
In Less, you get:
```less
@var: 1;
.box {
  @var: 2;
  val: @var; // value is 3
  @var: 3;
}
@new_var: @var;  // value is 1
```
